import React from "react";
import Link from "next/link";
import Head from "next/head";

const index = () => {
  return (
    <>
      <Head>
        <title>Movies page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Movies</h1>
        <section>
          <p>
            You&apos;re in the movies route, click <Link href="/">here</Link> to
            go back home
          </p>
          <p>
            Click <Link href="/movie/big">here</Link> to go to a movie route.
          </p>
        </section>
      </main>
    </>
  );
};

export default index;
