import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";

const Movie = () => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <>
      <Head>
        <title>{slug} page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Movie</h1>
        <section>
          <p>Movie in URL route is:{slug}</p>
          <p>Feel free to change this to get the title on the screen</p>
          <p>
            Click <Link href="/">here</Link> to go back home
          </p>
        </section>
      </main>
    </>
  );
};

export default Movie;
